enum ActionTypeKeys{
    GET_CURRENT_USER="GET_CURRENT_USER",
    GET_CURRENT_USER_SUCCESS ="GET_CURRENT_USER_SUCCESS",
    GET_CURRENT_USER_ERROR ="GET_CURRENT_USER_ERROR",
    GET_USER_INFO = "GET_USER_INFO",
    GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS",
    GET_USER_INFO_ERROR = "GET_USER_INFO_ERROR",
    ADD_TICKET_INPROGRESS = "ADD_TICKET_INPROGRESS",
    ADD_TICKET_SUCCESS = "ADD_TICKET_SUCCESS",
    ADD_TICKET_ERROR = "ADD_TICKET_ERROR",
    UPDATE_TICKET= "UPDATE_TICKET",  //TODO
    REMOVE_TICKET ="REMOVE_TICKET",  //TODO
    GET_TICKET= "GET_TICKET", //TODO
    GET_ALL_TICKETS = "GET_ALL_TICKETS",
    SET_TICKET_ID = "SET_TICKET_ID",
}

export default ActionTypeKeys;