enum ActionTypeKeys{
    GET_CURRENT_USER="GET_CURRENT_USER",
    GET_CURRENT_USER_SUCCESS ="GET_CURRENT_USER_SUCCESS",
    GET_CURRENT_USER_ERROR ="GET_CURRENT_USER_ERROR",
    GET_USER_INFO = "GET_USER_INFO",
    GET_USER_INFO_SUCCESS = "GET_USER_INFO_SUCCESS",
    GET_USER_INFO_ERROR = "GET_USER_INFO_ERROR",
}

export default ActionTypeKeys;