const constants = {
    
    //GENERIC USER-RELATED ACTIONS
    GET_USER:"GET_USER", //TODO
    GET_USERPROFILE_DATA:"GET_USERPROFILE_DATA",    //TODO
    FETCH_USER_CONTEXT: "FETCH_USER_CONTEXT", //TODO
    FETCH_SUBMITTER_REQUEST: "FETCH_SUBMITTER_REQUEST",//TOUPDATE
    FETCH_SUBMITTER_FAILURE: "FETCH_SUBMITTER_FAILURE", //TOUPDATE
    FETCH_SUBMITTER_SUCCESS: "FETCH_SUBMITTER_SUCCESS", //TOUPDATE
    INVALIDATE_SUBMITTER:"INVALIDATE_SUBMITTER",
   
    //GET & SET USER FIELD ACTIONS RELATED TO TICKET 
    SET_SUBMITTER:"SET_SUBMITTER",
    REQUEST_SUBMITTER_INFO: "REQUEST_SUBMITTER_INFO",
    RECEIVE_SUBMITTER_INFO: "RECEIVE_SUBMITTER_INFO",
    SET_RESPONSIBLE_INDIVIDUAL: "SET_RESPONSIBLE_INDIVIDUAL",
    ADD_WATCHER: "ADD_WATCHER",
    REMOVE_WATCHER: "REMOVE_WATCHER",
    GET_ALL_WATCHERS: "GET_ALL_WATCHERS",
    SET_ASSIGNEE: "SET_ASSIGNEE",
    SET_REVIEWER: "SET_REVIEWER",
    ADD_AUDIT_TEAM_CC: "ADD_AUDIT_TEAM_CC",
    REMOVE_AUDIT_TEAM_CC: "REMOVE_AUDIT_TEAM_CC",
    GET_ALL_AUDIT_TEAM: "GET_ALL_AUDIT_TEAM",
    
    //SYNCHRONOUS USER ACTIONS RELATED TO TICKETS 
    ADD_TICKET:"ADD_TICKET",
    UPDATE_TICKET:"UPDATE_TICKET",  //TODO
    REMOVE_TICKET:"REMOVE_TICKET",  //TODO
    GET_TICKET: "GET_TICKET", //TODO
    GET_ALL_TICKETS: "GET_ALL_TICKETS",
    SET_TICKET_ID: "SET_TICKET_ID", //TODO
    SET_ENGAGEMENT_NAME: "SET_ENGAGEMENT_NAME",
    SET_ENGAGEMENT_CHARGE_CODE: "SET_ENGAGEMENT_CHARGE_CODE",
    SET_ACCOUNTING_PERIOD_END: "SET_ACCOUNTING_PERIOD_END",
    SET_SUBJECT: "SET_SUBJECT",
    SET_DETAILED_ANALYSIS: "SET_DETAILED_ANALYSIS",
    REQUIRE_TRAINING: "REQUIRE_TRAINING",
    SET_FAQ: "SET_FAQ",
    SET_CONSULTATION: "SET_CONSULTATION",
    SET_CONCLUSION: "SET_CONCLUSION",
    ADD_TO_KB: "ADD_TO_KB",
    SET_PRIORITY: "SET_PRIORITY",
    SET_REASON_FOR_URGENCY: "SET_REASON_FOR_URGENCY",

    //SYNCHRONOUS USER ACTIONS RELATED TO TICKETS 
    ADD_LABEL: "ADD_LABEL",
    REMOVE_LABEL: "REMOVE_LABEL",
    SELECT_ENGAGEMENT_TYPE: "SELECT_ENGAGEMENT_TYPE",
    REMOVE_ENGAGEMENT_TYPE: "REMOVE_ENGAGEMENT_TYPE",
    SET_AUDITING_STANDARDS: "SET_AUDITING_STANDARDS",
    SET_CATEGORY: "SET_CATEGORY",
    ADD_ACCOUNTING_FRAMEWORK: "ADD_ACCOUNTING_FRAMEWORK",
    REMOVE_ACCOUNTING_FRAMEWORK: "REMOVE_ACCOUNTING_FRAMEWORK",
    ASSIGN_SUPPORT_TEAM: "ASSIGN_SUPPORT_TEAM", 
    ADD_TOPIC: "ADD_TOPIC",
    REMOVE_TOPIC: "REMOVE_TOPIC",
    ADD_COMMENT: "ADD_COMMENT",
    SET_COMMENT_OWNER: "SET_COMMENT_OWNER",
    REMOVE_COMMENT: "REMOVE_COMMENT",
    EDIT_COMMENT: "EDIT_COMMENT",
    SET_STATUS: "SET_STATUS",
    
    
    
    
    
    // get EDIT_COMMENT() {
    //     return this._EDIT_COMMENT;
    // },
    // set EDIT_COMMENT(value) {
    //     this._EDIT_COMMENT = value;
    // },

    //ASYNC DICTIONARY ACTIONS
    //------------------------//
    //engagement type      
    REQUEST_ENGAGEMENT_TYPES: "REQUEST_ENGAGEMENT_TYPES",
    RECEIVE_ENGAGEMENT_TYPES: "RECEIVE_ENGAGEMENT_TYPES",
    INVALIDATE_ENGAGEMENT_TYPES:"INVALIDATE_ENGAGEMENT_TYPES",
    FETCH_ENGAGEMENT_TYPES_FAILURE: "FETCH_ENGAGEMENT_TYPES_FAILURE", //TODO
    GET_ALL_ENGAGEMENT_TYPES: "GET_ALL_ENGAGEMENT_TYPES", //TODO

    
    GET_ALL_AUDITING_STANDARDS:"GET_ALL_AUDITING_STANDARDS", //TODO
    GET_ALL_CATEGORIES: "GET_ALL_CATEGORIES", //TODO
    GET_ALL_TOPICS: "GET_ALL_TOPICS", //TODO
    
    GET_ALL_LABELS: "GET_ALL_LABELS", //TODO
    GET_ALL_SUPPORT_TEAMS: "GET_ALL SUPPORT_TEAMS", //TODO
    GET_ALL_STATUSES: "GET_ALL_STATUSES", //TODO
        
    //GET & SET COMMENT ACTIONS RELATED TO TICKET
    GET_ALL_COMMENTS: "GET_ALL_COMMENTS", //TODO
    


    //FILE UPLOAD
    UPLOAD_FILE: "UPLOAD_FILE", //TODO
    REMOVE_FILE: "REMOVE_FILE", //TODO
    
    
    //UI
    SET_VISIBILITY_FILTER: "SET_VISIBILITY_FILTER",
    SHOW_ALL_FIELDS: "SHOW_ALL_FIELDS", //TODO
    HIDE_SUPPORT_FIELDS: "HIDE_SUPPORT_FIELDS", //TODO
    SHOW_MY_SUBMITTED:"SHOW_MY_SUBMITTED",
    SHOW_MY_UNASSIGNED:"SHOW_MY_UNASSIGNED",
    SHOW_MY_WATCHED:"SHOW_MY_WATCHED",
    
        
    ADD_QUERY: "ADD_QUERY",
    REMOVE_QUERY: "REMOVE_QUERY",
    
    FETCH_LABELS: "FETCH_LABELS",
    CANCEL_FETCHING: "CANCEL_FETCHING",
    CHANGE_SUGGESTIONS: "CHANGE_SUGGESTIONS",
    CLEAR_SUGGESTIONS: "CLEAR_SUGGESTIONS",

    
    ADD_ERROR: "ADD_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR",


}

export default constants