enum ActionTypeKeys {
  GET_CURRENT_USER_INPROGRESS = "GET_CURRENT_USER_INPROGRESS",
  GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS",
  GET_CURRENT_USER_ERROR = "GET_CURRENT_USER_ERROR",

  GET_SITE_INPROGRESS = "GET_SITE_INPROGRESS",
  GET_SITE_SUCCESS = "GET_SITE_SUCCESS",
  GET_SITE_ERROR = "GET_SITE_ERROR",

  GET_TICKET_DICTIONARY_INPROGRESS = "GET_TICKET_DICTIONARY_INPROGRESS",
  GET_TICKET_DICTIONARY_SUCCESS = "GET_TICKET_DICTIONARY_SUCCESS",
  GET_TICKET_DICTIONARY_ERROR = "GET_TICKET_DICTIONARY_ERROR"
}

export default ActionTypeKeys;
