enum ActionTypeKeys {
  GET_USERS_INPROGRESS = "GET_USERS_INPROGRESS",
  GET_USERS_SUCCESS = "GET_USERS_SUCCESS",
  GET_USERS_ERROR = "GET_USERS_ERROR",
  ADD_TICKET_INPROGRESS = "ADD_TICKET_INPROGRESS",
  ADD_TICKET_SUCCESS = "ADD_TICKET_SUCCESS",
  ADD_TICKET_ERROR = "ADD_TICKET_ERROR",
  UPDATE_TICKET = "UPDATE_TICKET", //TODO
  REMOVE_TICKET = "REMOVE_TICKET", //TODO
  GET_TICKET = "GET_TICKET", //TODO
  GET_ALL_TICKETS = "GET_ALL_TICKETS",
  SET_TICKET_ID = "SET_TICKET_ID",
  GET_CURRENT_DICTIONARY_INPROGRESS = "GET_CURRENT_DICTIONARY_INPROGRESS",
  GET_CURRENT_DICTIONARY_SUCCESS = "GET_CURRENT_DICTIONARY_SUCCESS",
  GET_ENGAGEMENTTYPE_SUCCESS = "GET_ENGAGEMENTTYPE_SUCCESS",
  GET_ACCOUNTINGFRAMEWORK_SUCCESS = "GET_ACCOUNTINGFRAMEWORK_SUCCESS",
  GET_AUDITINGSTANDARD_SUCCESS = "GET_AUDITINGSTANDARD_SUCCESS",
  GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS",
  GET_TOPIC_SUCCESS = "GET_TOPIC_SUCCESS",
  GET_TICKETTYPE_SUCCESS = "GET_TICKETTYPE_SUCCESS",
  GET_STATUS_SUCCESS = "GET_STATUS_SUCCESS",
  GET_CURRENT_DICTIONARY_ERROR = "GET_CURRENT_DICTIONARY_ERROR"
}

export default ActionTypeKeys;
