const constants = {
    
    //asynchronous network related user entity ACTIONS
    GET_USER:"GET_USER", //TODO
    GET_USERPROFILE_DATA:"GET_USERPROFILE_DATA",    //TODO
    FETCH_USER_CONTEXT: "FETCH_USER_CONTEXT", //TODO
    FETCH_SUBMITTER_REQUEST: "FETCH_SUBMITTER_REQUEST",//TOUPDATE
    FETCH_SUBMITTER_FAILURE: "FETCH_SUBMITTER_FAILURE", //TOUPDATE
    FETCH_SUBMITTER_SUCCESS: "FETCH_SUBMITTER_SUCCESS", //TOUPDATE
    INVALIDATE_SUBMITTER:"INVALIDATE_SUBMITTER",
   
    //GET & SET USER FIELD ACTIONS RELATED TO TICKET 
    SET_SUBMITTER:"SET_SUBMITTER",
    REQUEST_SUBMITTER_INFO: "REQUEST_SUBMITTER_INFO",
    RECEIVE_SUBMITTER_INFO: "RECEIVE_SUBMITTER_INFO",
    
    
    //SYNCHRONOUS USER ACTIONS RELATED TO TICKETS 
    ADD_TICKET:"ADD_TICKET",
    UPDATE_TICKET:"UPDATE_TICKET",  //TODO
    REMOVE_TICKET:"REMOVE_TICKET",  //TODO
    GET_TICKET: "GET_TICKET", //TODO
    GET_ALL_TICKETS: "GET_ALL_TICKETS",
    SET_TICKET_ID: "SET_TICKET_ID", //TODO
    SELECT_ENGAGEMENT_TYPE: "SELECT_ENGAGEMENT_TYPE",

    

    
    //ASYNC IDictionaryState ACTIONS
    //------------------------//
    //engagement type      
    REQUEST_ENGAGEMENT_TYPES: "REQUEST_ENGAGEMENT_TYPES",
    RECEIVE_ENGAGEMENT_TYPES: "RECEIVE_ENGAGEMENT_TYPES",
    INVALIDATE_ENGAGEMENT_TYPES:"INVALIDATE_ENGAGEMENT_TYPES",
    FETCH_ENGAGEMENT_TYPES_FAILURE: "FETCH_ENGAGEMENT_TYPES_FAILURE", //TODO
    GET_ALL_ENGAGEMENT_TYPES: "GET_ALL_ENGAGEMENT_TYPES", //TODO

    
    GET_ALL_AUDITING_STANDARDS:"GET_ALL_AUDITING_STANDARDS", //TODO
    GET_ALL_CATEGORIES: "GET_ALL_CATEGORIES", //TODO
    GET_ALL_TOPICS: "GET_ALL_TOPICS", //TODO
    
    GET_ALL_LABELS: "GET_ALL_LABELS", //TODO
    GET_ALL_SUPPORT_TEAMS: "GET_ALL SUPPORT_TEAMS", //TODO
    GET_ALL_STATUSES: "GET_ALL_STATUSES", //TODO

    FETCH_LABELS: "FETCH_LABELS",
    CANCEL_FETCHING: "CANCEL_FETCHING",
    CHANGE_SUGGESTIONS: "CHANGE_SUGGESTIONS",
    CLEAR_SUGGESTIONS: "CLEAR_SUGGESTIONS",

        
    //GET & SET COMMENT ACTIONS RELATED TO TICKET
    GET_ALL_COMMENTS: "GET_ALL_COMMENTS", //TODO
    ADD_COMMENT: "ADD_COMMENT",
    REMOVE_COMMENT: "REMOVE_COMMENT",
    EDIT_COMMENT: "EDIT_COMMENT",


    //FILE UPLOAD
    UPLOAD_FILE: "UPLOAD_FILE", //TODO
    REMOVE_FILE: "REMOVE_FILE", //TODO
    
    
    //UI
    SET_VISIBILITY_FILTER: "SET_VISIBILITY_FILTER",
    SHOW_ALL_FIELDS: "SHOW_ALL_FIELDS", //TODO
    HIDE_SUPPORT_FIELDS: "HIDE_SUPPORT_FIELDS", //TODO
    SHOW_MY_SUBMITTED:"SHOW_MY_SUBMITTED",
    SHOW_MY_UNASSIGNED:"SHOW_MY_UNASSIGNED",
    SHOW_MY_WATCHED:"SHOW_MY_WATCHED",
    
        
    ADD_QUERY: "ADD_QUERY",
    REMOVE_QUERY: "REMOVE_QUERY",
    

    
    ADD_ERROR: "ADD_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR",


}

export default constants