const constants = {
    SET_ID: "SET_ID",
    FETCH_USER_CONTEXT:"FETCH_USER_CONTEXT", 
    SET_VISIBILITY_FILTER: "SET_VISIBILITY_FILTER", //UI
    SET_SUBMITTER:"SET_SUBMITTER", //user?
    ADD_ERROR:"ADD_ERROR", //message
    CLEAR_ERROR:"CLEAR_ERROR", //index
    ADD_AUDIT_TEAM_CC: "ADD_AUDIT_TEAM_CC",     //user?
    REMOVE_AUDIT_TEAM_CC: "REMOVE_AUDIT_TEAM_CC",      //user? 
    SET_RESPONSIBLE_INDIVIDUAL: "SET_RESPONSIBLE_INDIVIDUAL",       //user?
    SET_ENGAGEMENT_NAME: "SET_ENGAGEMENT_NAME",             //text
    SET_ENGAGEMENT_CHARGE_CODE: "SET_ENGAGEMENT_CHARGE_CODE",
    SET_ACCOUNTING_PERIOD_END: "SET_ACCOUNTING_PERIOD_END",
    ADD_ENGAGEMENT_TYPE: "ADD_ENGAGEMENT_TYPE",             //text
    REMOVE_ENGAGEMENT_TYPE: "REMOVE_ENGAGEMENT_TYPE",
    SET_AUDITING_STANDARDS: "SET_AUDITING_STANDARDS",
    ADD_ACCOUNTING_FRAMEWORK: "ADD_ACCOUNTING_FRAMEWORK",       //index
    REMOVE_ACCOUNTING_FRAMEWORK: "REMOVE_ACCOUNTING_FRAMEWORK",     //index
    SET_CATEGORY: "SET_CATEGORY",           //index
    ADD_TOPIC: "ADD_TOPIC",
    CLEAR_TOPIC: "CLEAR_TOPIC",
    SET_SUBJECT: "SET_SUBJECT",
    SET_DETAILED_ANALYSIS: "SET_DETAILED_ANALYSIS",
    SET_QUESTION: "SET_QUESTION",
    SET_PRIORITY: "SET_PRIORITY",     //index
    SET_REASON_FOR_URGENCY: "SET_REASON_FOR_URGENCY",
    UPLOAD_FILE: "UPLOAD_FILE",
    REMOVE_FILE: "REMOVE_FILE",
    ADD_WATCHER: "ADD_WATCHER", //USER  
    REMOVE_WATCHER:"REMOVE_WATCHER",        //index
    ADD_COMMENT: "ADD_COMMENT",             //index
    REMOVE_COMMENT: "REMOVE_COMMENT",       //index
    EDIT_COMMENT: "EDIT_COMMENT",              //index
    SET_STATUS: "SET_STATUS",               //index
    ADD_QUERY:"ADD_QUERY",              //index
    REMOVE_QUERY: "REMOVE_QUERY"       //index
    
}

export default constants