const constants = {
    FETCH_USER_CONTEXT:"FETCH_USER_CONTEXT", 
    SET_VISIBILITY_FILTER: "SET_VISIBILITY_FILTER", //UI
    ADD_SUBMITTER:"ADD_SUBMITTER", //user?
    CHANGE_SUBMITTER:"CHANGE_SUBMITTER", //user?
    ADD_ERROR:"ADD_ERROR", //message
    CLEAR_ERROR:"CLEAR_ERROR", //index
    ADD_AUDIT_TEAM_CC: "ADD_AUDIT_TEAM_CC",     //user?
    REMOVE_AUDIT_TEAM_CC: "REMOVE_AUDIT_TEAM_CC",      //user? 
    ADD_RESPONSIBLE_INDIVIDUAL: "ADD_RESPONSIBLE_INDIVIDUAL",       //user?
    REMOVE_RESPONSIBLE_INDIVIDUAL: "REMOVE_RESPONSIBLE_INDIVIDUAL",     //user?
    ADD_QUERY:"ADD_QUERY",              //index
    REMOVE_QUERY: "REMOVE_QUERY",       //index
    ADD_ENGAGEMENT_TYPE: "ADD_ENGAGEMENT_TYPE",             //text
    REMOVE_ENGAGEMENT_TYPE: "REMOVE_ENGAGEMENT_TYPE",
    ADD_AUDITING_STANDARDS: "ADD_AUDITING_STANDARDS",
    REMOVE_AUDITING_STANDARDS: "REMOVE_AUDITING_STANDARDS",
    ADD_ACCOUNT_FRAMEWORK: "ADD_AUDITING_FRAMEWORK",       //index
    REMOVE_ACCOUNT_FRAMEWORK: "REMOVE_AUDITING_FRAMEWORK",     //index
    SET_STATUS: "SET_STATUS",               //index
    SET_PRIORITY: "SET_PRIORITY",     //index
    ADD_CATEGORY: "ADD_CATEGORY",           //index
    CHANGE_CATEGORY: "CHANGE_CATEGORY",     //index
    ADD_WATCHER: "ADD_WATCHER", //USER  
    REMOVE_WATCHER:"REMOVE_WATCHER",        //index
    ADD_COMMENT: "ADD_COMMENT",             //index
    REMOVE_COMMENT: "REMOVE_COMMENT",       //index
    EDIT_COMMENT: "EDIT_COMMENT"              //index

}

export default constants