"use strict";
exports.__esModule = true;
var constants = {
    ADD_SUBMITTER: "ADD_SUBMITTER",
    REMOVE_SUBMITTER: "REMOVE_SUBMITTER",
    ADD_ERROR: "ADD_ERROR",
    CLEAR_ERROR: "CLEAR_ERROR",
    ADD_AUDIT_TEAM_CC: "ADD_AUDIT_TEAM_CC",
    REMOVE_AUDIT_TEAM_CC: "REMOVE_AUDIT_TEAM_CC",
    ADD_RESPONSIBLE_INDIVIDUAL: "_RESPONSIBLE_INDIVIDUAL",
    ADD_QUERY_INFO: "ADD_QUERY_INFO",
    REMOVE_QUERY_INFO: "REMOVE_QUERY_INFO",
    ADD_DICTIONARY_ITEM: "ADD_DICTIONARY_ITEM",
    REMOVE_DICTIONARY_ITEM: "REMOVE DICTIONARY_ITEM",
    // ADD_ENGAGEMENT_TYPE: "ADD_ENGAGEMENT_TYPE",
    // REMOVE_ENGAGEMENT_TYPE: "REMOVE_ENGAGEMENT_TYPE",
    // ADD_AUDITING_FRAMEWORK: "ADD_AUDITING_FRAMEWORK",
    // REMOVE_AUDITING_FRAMEWORK: "REMOVE_AUDITING_FRAMEWORK",
    // ADD_STATUS: "ADD_STATUS",
    // REMOVE_STATUS: "REMOVE_STATUS",
    // CHANGE_PRIORITY: "CHANGE_PRIORITY",
    ADD_CATEGORY: "ADD_CATEGORY",
    REMOVE_CATEGORY: "REMOVE_CATEGORY",
    ADD_WATCHER: "ADD_WATCHER",
    REMOVE_WATCHER: "REMOVE_WATCHER",
    ADD_COMMENT: "ADD_COMMENT",
    REMOVE_COMMENT: "REMOVE_COMMENT"
};
exports["default"] = constants;
